export interface PrepDay {
  day: number;
  title: string;
  yogaPose: string;
  dietaryTip: string;
  mindfulnessExercise: string;
  packingItem: string;
}

export const prepProgram: PrepDay[] = [
  { day: 1, title: 'Set Your Intentions', yogaPose: 'Mountain Pose (Tadasana) — stand tall, feel rooted', dietaryTip: 'Begin reducing caffeine — switch your afternoon coffee to green tea', mindfulnessExercise: 'Write down 3 intentions for your retreat', packingItem: 'Yoga mat (or confirm rental)' },
  { day: 2, title: 'Morning Sun Salutations', yogaPose: 'Sun Salutation A — 3 rounds to greet the day', dietaryTip: 'Add a green smoothie to your morning routine', mindfulnessExercise: '5-minute gratitude meditation', packingItem: 'Comfortable yoga clothes (2-3 sets)' },
  { day: 3, title: 'Open Your Heart', yogaPose: 'Cobra Pose (Bhujangasana) — gentle heart opener', dietaryTip: 'Try one fully plant-based meal today', mindfulnessExercise: 'Heart-centered breathing: inhale love, exhale tension', packingItem: 'Sunscreen SPF 50+' },
  { day: 4, title: 'Ground & Balance', yogaPose: 'Tree Pose (Vrksasana) — find your center', dietaryTip: 'Hydrate: aim for 8 glasses of water today', mindfulnessExercise: 'Barefoot walking on grass for 10 minutes', packingItem: 'Reusable water bottle' },
  { day: 5, title: 'Strength & Grace', yogaPose: 'Warrior II (Virabhadrasana II) — embody strength', dietaryTip: 'Reduce sugar intake — swap dessert for fresh fruit', mindfulnessExercise: 'Body scan meditation before bed (10 min)', packingItem: 'Light layers for evening' },
  { day: 6, title: 'Flexibility Flow', yogaPose: 'Forward Fold (Uttanasana) — let go of tension', dietaryTip: 'Add turmeric to your meals — anti-inflammatory powerhouse', mindfulnessExercise: 'Journaling: what do you want to release?', packingItem: 'Journal and pen' },
  { day: 7, title: 'Rest & Restore', yogaPose: 'Child\'s Pose (Balasana) — surrender and rest', dietaryTip: 'Prepare a nourishing soup with seasonal vegetables', mindfulnessExercise: 'Digital detox: 2 hours with phone off', packingItem: 'Comfortable sleepwear' },
  { day: 8, title: 'Breathe Deeply', yogaPose: 'Easy Seat (Sukhasana) — pranayama practice', dietaryTip: 'Eat mindfully today — no screens during meals', mindfulnessExercise: '4-7-8 breathing: 5 rounds before bed', packingItem: 'Eye mask for flights and sleep' },
  { day: 9, title: 'Core Connection', yogaPose: 'Boat Pose (Navasana) — activate your center', dietaryTip: 'Start your day with warm lemon water', mindfulnessExercise: 'Set a timer: 1 minute of silence every hour', packingItem: 'Sandals or flip-flops' },
  { day: 10, title: 'Twist & Detox', yogaPose: 'Seated Twist (Ardha Matsyendrasana) — wring out tension', dietaryTip: 'Eliminate processed foods for the day', mindfulnessExercise: 'Write a letter to your future self at the retreat', packingItem: 'Swimsuit (2 recommended)' },
  { day: 11, title: 'Hip Opening', yogaPose: 'Pigeon Pose (Eka Pada Rajakapotasana) — release stored emotions', dietaryTip: 'Try a new herbal tea — chamomile, peppermint, or rooibos', mindfulnessExercise: 'Loving-kindness meditation for 10 minutes', packingItem: 'Hat or visor for sun protection' },
  { day: 12, title: 'Inversion Play', yogaPose: 'Legs Up the Wall (Viparita Karani) — calming inversion', dietaryTip: 'Prepare overnight oats with chia seeds and berries', mindfulnessExercise: 'Evening walk in nature — notice 5 things you see, hear, smell', packingItem: 'Light hiking shoes or trainers' },
  { day: 13, title: 'Shoulder Love', yogaPose: 'Eagle Arms (Garudasana arms) — release shoulder tension', dietaryTip: 'Snack on nuts and seeds — almonds, walnuts, pumpkin seeds', mindfulnessExercise: 'Progressive muscle relaxation before sleep', packingItem: 'Light scarf or shawl' },
  { day: 14, title: 'Half Moon Rise', yogaPose: 'Half Moon Pose (Ardha Chandrasana) — build confidence', dietaryTip: 'Cook a colorful Buddha bowl with at least 5 different vegetables', mindfulnessExercise: 'Midday pause: 3 conscious breaths before each meal', packingItem: 'Toiletries (travel size)' },
  { day: 15, title: 'Halfway Celebration', yogaPose: 'Dancer\'s Pose (Natarajasana) — celebrate progress', dietaryTip: 'Make a tropical smoothie bowl — mango, banana, coconut', mindfulnessExercise: 'Reflect on the past 2 weeks — journal your growth', packingItem: 'Camera or ensure phone storage space' },
  { day: 16, title: 'Flow State', yogaPose: 'Vinyasa Flow — link 5 poses with breath', dietaryTip: 'Try a Mediterranean salad with olive oil and fresh herbs', mindfulnessExercise: 'Moving meditation: yoga with eyes closed', packingItem: 'Books or Kindle for downtime reading' },
  { day: 17, title: 'Standing Strong', yogaPose: 'Warrior III (Virabhadrasana III) — focus and balance', dietaryTip: 'Reduce alcohol intake — try kombucha or sparkling water with citrus', mindfulnessExercise: 'Power pose for 2 minutes — research says it boosts confidence', packingItem: 'Earplugs for travel' },
  { day: 18, title: 'Spine Health', yogaPose: 'Cat-Cow (Marjaryasana-Bitilasana) — spinal flexibility', dietaryTip: 'Omega-3 boost: add flaxseed or walnuts to your breakfast', mindfulnessExercise: 'Spine-focused body awareness: notice your posture 5 times today', packingItem: 'Travel adapter/charger' },
  { day: 19, title: 'Inner Calm', yogaPose: 'Lotus Prep (Ardha Padmasana) — hip flexibility', dietaryTip: 'Prepare a calming golden milk before bed', mindfulnessExercise: 'Yoga Nidra guided practice (20 minutes)', packingItem: 'Small first-aid kit' },
  { day: 20, title: 'Power & Presence', yogaPose: 'Chair Pose (Utkatasana) — build inner fire', dietaryTip: 'Iron-rich meal: lentil soup with spinach and cumin', mindfulnessExercise: 'Stand in nature for 5 minutes — just be present', packingItem: 'Laundry bag for worn clothes' },
  { day: 21, title: 'Gentle Flow', yogaPose: 'Supine Twist (Supta Matsyendrasana) — wind down', dietaryTip: 'Magnesium-rich dinner: dark leafy greens, avocado, banana', mindfulnessExercise: 'Candle gazing (Trataka) meditation for 5 minutes', packingItem: 'Resistance band (optional)' },
  { day: 22, title: 'Arm Strength', yogaPose: 'Plank to Chaturanga — build upper body strength', dietaryTip: 'Protein-rich lunch: quinoa salad with chickpeas and tahini', mindfulnessExercise: 'Gratitude list: 10 things you are grateful for right now', packingItem: 'Portable yoga strap' },
  { day: 23, title: 'Back Bending', yogaPose: 'Bridge Pose (Setu Bandhasana) — open the front body', dietaryTip: 'Probiotic boost: add sauerkraut, kimchi, or yogurt to a meal', mindfulnessExercise: 'Listen to calming music for 15 minutes with eyes closed', packingItem: 'Comfortable travel outfit' },
  { day: 24, title: 'Meditation Deepening', yogaPose: 'Hero Pose (Virasana) — sitting in stillness', dietaryTip: 'Try intermittent fasting — 14-hour window (dinner to breakfast)', mindfulnessExercise: 'Extend morning meditation to 15 minutes', packingItem: 'Kindle/book for the journey' },
  { day: 25, title: 'Full Body Flow', yogaPose: 'Sun Salutation B — 5 complete rounds', dietaryTip: 'Rainbow eating challenge: eat fruits/veggies of 6 different colors', mindfulnessExercise: 'Walking meditation: 20 minutes of slow, mindful steps', packingItem: 'Small daypack for excursions' },
  { day: 26, title: 'Surrender Practice', yogaPose: 'Reclined Butterfly (Supta Baddha Konasana) — open and receive', dietaryTip: 'Prepare your favorite healthy comfort food — with love', mindfulnessExercise: 'Write down fears about the retreat, then write counterpoints', packingItem: 'Dressy-casual outfit for dinner out' },
  { day: 27, title: 'Energize', yogaPose: 'Camel Pose (Ustrasana) — energy and heart opening', dietaryTip: 'Matcha latte with oat milk — sustained energy without jitters', mindfulnessExercise: 'Dance freely to your favorite song — pure joy movement', packingItem: 'Snacks for travel day' },
  { day: 28, title: 'Connect & Share', yogaPose: 'Partner stretch or self-massage sequence', dietaryTip: 'Share a plant-based meal with a friend or family member', mindfulnessExercise: 'Tell someone you love them — genuine connection practice', packingItem: 'Small gifts to share with retreat friends (optional)' },
  { day: 29, title: 'Final Preparation', yogaPose: 'Full practice: your 5 favorite poses in a flow', dietaryTip: 'Light, easily digestible dinner — you are almost there', mindfulnessExercise: 'Visualization: imagine arriving at the retreat, feeling at peace', packingItem: 'Do final packing — check everything off your list' },
  { day: 30, title: 'You Are Ready', yogaPose: 'Savasana (Corpse Pose) — complete surrender and trust', dietaryTip: 'Travel day nutrition: pack fruit, nuts, and water for the journey', mindfulnessExercise: 'Set one final intention. Breathe. You are ready.', packingItem: 'Passport, tickets, and confirmation — you are on your way!' },
];
